# Generated by Django 5.2.6 on 2025-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_compound_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
